ospi:
  password: "YOUR_OSPI_PASSWORD" # Needs to be hashed. View README for help
  port: "8080"
stations: # Station activity notifications for start and stop. Valid options are "yes" or "no"
  notify:
    start: "yes"
    stop: "yes"
  messages: # Use {} as the place where the station name will be displayed
    start: "{} is now active"
    stop: "{} is now idle" 
rain: # Rain sensor notifications for active or cleared. Valid options are "yes" or "no"
  notify: "yes"
  messages:
    active: "Rain sensor has detected rain"
    clear: "Rain sensor has cleared"
waterlevel: # Water level notifications? Valid options are "yes" or "no"
  notify: "yes"
  message: "The water level is now {}%"
push:
  service: "instapush" # Acceptable options are "instapush" or "pushover" or "ifttt"
  instapush:
    appID: "YOUR_INSTAPUSH_APPID"
    appSecret: "YOUR_INSTAPUSH_APPSECRET"
  pushover:
    userKey: "YOUR_PUSHOVER_USERKEY"
    appToken: "YOUR_PUSHOVER_APPTOKEN"
  ifttt:
    eventName: "YOUR_IFTTT_EVENT_NAME"
    userKey: "YOUR_IFTTT_USER_KEY"
email:
  from: "you@yourdomain.com"
  to: "you@yourdomain.com"
  subject: "OSPi Push Notification Script Failure"
  text: "The OSPi push notification script has crashed, or stopped. The error reported was: {}"
  server: "localhost" # Valid options are "localhost" or "gmail". Using GMail will reduce the email being flagged as spam
  gmailUsername: "YOUR_GMAIL_USERNAME"
  gmailPassword: "YOUR_GMAIL_PASSWORD"
